name: Deploy

# Explicitly declare permissions
permissions:
  actions: read

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

env:
  BUILD_PATH: 'out'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # Cancel in progress runs if a new run is started

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    outputs:
      cid: ${{ steps.deploy.outputs.cid }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ${{ env.BUILD_PATH }}
          run-id: ${{ github.event.workflow_run.id }}

      - uses: ipfs/ipfs-deploy-action@v1
        name: Deploy to IPFS Mirror Providers
        id: deploy
        with:
          path-to-deploy: ${{ env.BUILD_PATH }}
          cluster-url: "/dnsaddr/ipfs-websites.collab.ipfscluster.io"
          cluster-user: ${{ secrets.CLUSTER_USER }}
          cluster-password: ${{ secrets.CLUSTER_PASSWORD }}
          storacha-key: ${{ secrets.STORACHA_KEY }}
          storacha-proof: ${{ secrets.STORACHA_PROOF }}
          #TODO pinata-jwt-token: ${{ secrets.PINATA_JWT_TOKEN }}
          github-token: ${{ github.token }}

      # TODO: right now, DNSLink is controlled by Fleek, and we use ipfs/ipfs-deploy-action for PR previews
      #- name: Update DNSLink
      #  if: false # TODO github.ref == 'refs/heads/main' # only update DNSLink for main branch
      #  uses: ipfs/dnslink-action@v0.1
      #  with:
      #    cid: ${{ steps.deploy.outputs.cid }}
      #    dnslink_domain: 'specs.ipfs.tech'
      #    cf_record_id: ${{ secrets.CF_RECORD_ID }}
      #    cf_zone_id: ${{ secrets.CF_ZONE_ID }}
      #    cf_auth_token: ${{ secrets.CF_AUTH_TOKEN }}
      #    github_token: ${{ github.token }}
      #    set_github_status: true
